server:
  port: 8080
spring:
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/imsidb2?useSSL=false&serverTimezone=UTC
    username: root
    password: dkrakek1
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL57Dialect
    properties:
      hibernate:
        dialect.storage_engine: innodb
        show_sql: true
        format_sql: true
    show-sql: true
  session:
    store-type: jdbc
  thymeleaf:
    cache: false
jwt:
  secret: 1q2w3e
  expiration: 3600  # 1시간 (단위: 초)

  springdoc:
    version: 1.6.9
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
      configUrl: /api-docs/swagger-config
